# generated by linuxdeploy-plugin-qt

# try to make Qt apps more "native looking" on Gtk-based desktops, if possible
# on other desktops, use the XDG Desktop Portal plugin instead to get native dialogs
# see https://github.com/AppImage/AppImageKit/issues/977#issue-462374883
# and https://github.com/linuxdeploy/linuxdeploy-plugin-qt/pull/63
case "${XDG_CURRENT_DESKTOP}" in
    *KDE*|*kde*)
        export QT_QPA_PLATFORMTHEME=qt5ct
        ;;
    *GNOME*|*gnome*|*XFCE*)
        export QT_QPA_PLATFORMTHEME=gtk3
        ;;
    *)
        export QT_QPA_PLATFORMTHEME=xdgdesktopportal
        ;;
esac
